application: rocketsimulator
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
 
- url: /(.*\.(html))
  static_files: HTML/\1
  upload: HTML/(.*\.(html))
  
- url: /js
  static_dir: js
  
- url: /.*
  script: rocketsimulator.py
  

  
